import type { NodeData, EdgeData } from '../types';

export function generateDockerCompose(nodes: NodeData[], edges: EdgeData[]): string {
  const serviceBlocks: string[] = [];

  nodes.forEach((node) => {
    // Determine image
    let image = node.dockerImage || 'alpine:latest';
    let ports: string[] = [];
    let environment: string[] = [
      `SERVICE_NAME=${node.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}`,
      `TIER=${node.tier.split(' ')[0]}`,
      `PORT=8080`,
    ];

    if (node.type === 'database') {
      ports = ['"5432:5432"'];
      environment.push('POSTGRES_DB=livingspec_db', 'POSTGRES_USER=admin', 'POSTGRES_PASSWORD=secret_password_change_me');
    } else if (node.type === 'cache') {
      ports = ['"6379:6379"'];
    } else if (node.type === 'queue') {
      ports = ['"9092:9092"', '"5672:5672"'];
    } else if (node.type === 'gateway' || node.type === 'cdn') {
      ports = ['"80:80"', '"443:443"'];
    } else if (node.type === 'service') {
      ports = [`"${8000 + Math.floor(Math.random() * 900)}:8080"`];
    }

    // Downstream dependencies
    const outgoingEdges = edges.filter(e => e.from === node.id);
    const dependsOn = outgoingEdges.map(e => {
      const targetNode = nodes.find(n => n.id === e.to);
      return targetNode ? targetNode.name.toLowerCase().replace(/[^a-z0-9]/g, '-') : null;
    }).filter(Boolean);

    const serviceName = node.name.toLowerCase().replace(/[^a-z0-9]/g, '-');
    
    let block = `  ${serviceName}:\n`;
    block += `    image: ${image}\n`;
    block += `    container_name: livingspec-${serviceName}\n`;
    block += `    restart: unless-stopped\n`;
    
    if (ports.length > 0) {
      block += `    ports:\n`;
      ports.forEach(p => block += `      - ${p}\n`);
    }

    if (environment.length > 0) {
      block += `    environment:\n`;
      environment.forEach(env => block += `      - ${env}\n`);
    }

    if (dependsOn.length > 0) {
      block += `    depends_on:\n`;
      dependsOn.forEach(dep => block += `      - ${dep}\n`);
    }

    block += `    networks:\n`;
    block += `      - livingspec-mesh\n`;

    serviceBlocks.push(block);
  });

  return `# ==============================================================================
# LivingSpec Generated Docker Compose Topology
# Auto-generated by LivingSpec Architecture Engine
# Generated on: ${new Date().toISOString()}
# ==============================================================================

version: '3.8'

services:
${serviceBlocks.join('\n')}

networks:
  livingspec-mesh:
    driver: bridge
    ipam:
      driver: default
`;
}

export function generateTerraform(nodes: NodeData[], _edges: EdgeData[]): string {
  return `/**
 * ==============================================================================
 * LivingSpec Architecture Infrastructure as Code (Terraform AWS Definition)
 * Auto-generated by LivingSpec Architecture Engine
 * ==============================================================================
 */

terraform {
  required_version = ">= 1.7.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
  default_tags {
    tags = {
      Project     = "LivingSpec Architecture"
      ManagedBy   = "LivingSpec"
      Environment = "Production"
    }
  }
}

# --- VPC & Networking Mesh ---
resource "aws_vpc" "main" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_hostnames = true
  enable_dns_support   = true

  tags = {
    Name = "livingspec-vpc"
  }
}

resource "aws_subnet" "public" {
  count                   = 2
  vpc_id                  = aws_vpc.main.id
  cidr_block              = "10.0.\${count.index + 1}.0/24"
  availability_zone       = data.aws_availability_zones.available.names[count.index]
  map_public_ip_on_launch = true

  tags = {
    Name = "livingspec-public-\${count.index + 1}"
  }
}

data "aws_availability_zones" "available" {
  state = "available"
}

# --- ECS Cluster for Microservices ---
resource "aws_ecs_cluster" "mesh_cluster" {
  name = "livingspec-mesh-cluster"

  setting {
    name  = "containerInsights"
    value = "enabled"
  }
}

${nodes.filter(n => n.type === 'service' || n.type === 'gateway').map(node => {
  const safeName = node.name.toLowerCase().replace(/[^a-z0-9]/g, '_');
  return `# --- Service: ${node.name} (${node.tier}) ---
resource "aws_ecs_task_definition" "${safeName}_task" {
  family                   = "${safeName}"
  network_mode             = "awsvpc"
  requires_compatibilities = ["FARGATE"]
  cpu                      = "${node.metrics.cpuPercent > 40 ? '1024' : '512'}"
  memory                   = "${node.metrics.memoryMb > 1000 ? '2048' : '1024'}"

  container_definitions = jsonencode([
    {
      name      = "${safeName}"
      image     = "${node.dockerImage || 'nginx:alpine'}"
      essential = true
      portMappings = [
        {
          containerPort = 8080
          hostPort      = 8080
        }
      ]
      environment = [
        { name = "NODE_ENV", value = "production" },
        { name = "OWNER_TEAM", value = "${node.ownerTeam}" },
        { name = "CIRCUIT_BREAKER_ENABLED", value = "${node.circuitBreaker.enabled}" }
      ]
    }
  ])
}
`;
}).join('\n')}

${nodes.filter(n => n.type === 'database').map(node => {
  const safeName = node.name.toLowerCase().replace(/[^a-z0-9]/g, '_');
  return `# --- Database: ${node.name} ---
resource "aws_db_instance" "${safeName}" {
  identifier             = "${safeName.replace(/_/g, '-')}"
  engine                 = "postgres"
  engine_version         = "16.1"
  instance_class         = "db.r6g.large"
  allocated_storage      = 100
  max_allocated_storage  = 1000
  multi_az               = true
  publicly_accessible    = false
  skip_final_snapshot    = true
  username               = "db_admin"
  password               = "CHANGE_ME_SECRET_KEY"
  vpc_security_group_ids = [aws_vpc.main.default_security_group_id]
}
`;
}).join('\n')}

${nodes.filter(n => n.type === 'cache').map(node => {
  const safeName = node.name.toLowerCase().replace(/[^a-z0-9]/g, '_');
  return `# --- Cache: ${node.name} ---
resource "aws_elasticache_cluster" "${safeName}" {
  cluster_id           = "${safeName.replace(/_/g, '-')}"
  engine               = "redis"
  node_type            = "cache.m6g.large"
  num_cache_nodes      = 2
  parameter_group_name = "default.redis7"
  port                 = 6379
}
`;
}).join('\n')}
`;
}

export function generateMarkdownDoc(nodes: NodeData[], edges: EdgeData[], presetName: string): string {
  let doc = `# 📐 LivingSpec Architectural Specification: ${presetName}\n\n`;
  doc += `> *Autogenerated Living Architecture Document with real-time operational contracts, SLAs, and runbooks.*\n\n`;
  doc += `**Export Date:** ${new Date().toLocaleString()}  \n`;
  doc += `**Total Nodes:** ${nodes.length}  \n`;
  doc += `**Total Interconnects:** ${edges.length}  \n\n`;

  doc += `## 1. System Topology Overview\n\n`;
  doc += `| Component Name | Type | SLA Tier | Tech Stack | Current RPS | Error Rate |\n`;
  doc += `| :--- | :--- | :--- | :--- | :--- | :--- |\n`;
  nodes.forEach(n => {
    doc += `| **${n.name}** | \`${n.type}\` | ${n.tier} | ${n.techStack.join(', ')} | ${n.metrics.currentRps.toLocaleString()} | ${(n.metrics.errorRate * 100).toFixed(2)}% |\n`;
  });

  doc += `\n## 2. Component Runbooks & Incident Response\n\n`;
  nodes.forEach(n => {
    doc += `### ${n.name} (${n.type.toUpperCase()})\n`;
    doc += `- **Team Owner:** ${n.ownerTeam}\n`;
    doc += `- **Description:** ${n.description}\n`;
    doc += `- **Circuit Breaker:** ${n.circuitBreaker.enabled ? `✅ Active (Threshold: ${n.circuitBreaker.failureThreshold} errors, Timeout: ${n.circuitBreaker.resetTimeoutMs}ms)` : '❌ Disabled'}\n`;
    doc += `- **Rate Limiter:** ${n.rateLimiter.enabled ? `✅ Capacity: ${n.rateLimiter.capacity} req/s` : '❌ Disabled'}\n\n`;
    doc += `#### Runbook Procedures\n${n.runbook}\n\n`;
    if (n.endpoints.length > 0) {
      doc += `#### API Endpoints Contract\n`;
      n.endpoints.forEach(ep => {
        doc += `- \`${ep.method} ${ep.path}\` -> Returns \`${ep.statusCode}\` (~${ep.latencyMs}ms) - *${ep.description}*\n`;
      });
      doc += `\n`;
    }
    doc += `---\n\n`;
  });

  doc += `## 3. Inter-Service Communication Matrix\n\n`;
  doc += `| Source | Target | Protocol | Base Latency | Bandwidth Limit | Status |\n`;
  doc += `| :--- | :--- | :--- | :--- | :--- | :--- |\n`;
  edges.forEach(e => {
    const fromNode = nodes.find(n => n.id === e.from)?.name || e.from;
    const toNode = nodes.find(n => n.id === e.to)?.name || e.to;
    doc += `| ${fromNode} | ${toNode} | \`${e.protocol}\` | ${e.baseLatencyMs}ms | ${e.bandwidthLimitRps} RPS | \`${e.status}\` |\n`;
  });

  return doc;
}
