import type { ArchitecturePreset } from '../types';

export const ARCHITECTURE_PRESETS: ArchitecturePreset[] = [
  {
    id: 'ecommerce-distributed',
    name: 'E-Commerce Cloud Architecture',
    description: 'Enterprise event-driven microservices with Redis caching, Kafka messaging, and resilient PostgreSQL clustering.',
    badge: 'Production Ready',
    nodes: [
      {
        id: 'node-client',
        name: 'Web & Mobile Apps',
        type: 'client',
        category: 'client',
        region: 'us-east-1',
        x: 80,
        y: 280,
        width: 175,
        height: 105,
        status: 'healthy',
        techStack: ['Next.js 14', 'React Native', 'TypeScript'],
        ownerTeam: 'Frontend Core',
        tier: 'Tier 1 (Mission Critical)',
        description: 'Global client apps serving web browsers and native mobile applications with client-side telemetry.',
        runbook: '### Client Failover Runbook\n- When gateway error rate > 5%, trigger client exponential retry backoff.\n- Enable offline local caching with IndexedDB.\n- Redirect heavy traffic to Cloudflare waiting room if queue depth exceeds SLA.',
        endpoints: [],
        metrics: {
          currentRps: 2450,
          avgLatencyMs: 14,
          errorRate: 0.001,
          cpuPercent: 18,
          memoryMb: 256,
          maxMemoryMb: 1024,
          activeConnections: 18400,
          queueDepth: 0,
          currentReplicas: 3,
        },
        processing: {
          baseProcessingTimeMs: 4,
          concurrencyLimit: 5000,
          workerThreads: 8,
          clientGeneratedRps: 2400,
        },
        autoscaling: { enabled: true, minReplicas: 2, maxReplicas: 10, cpuThresholdPercent: 70, scaleUpCooldownMs: 6000, lastScaleTime: 0 },
        connectionPool: { enabled: false, maxPoolSize: 100, activeConnections: 0, connectionTimeoutMs: 500 },
        retryPolicy: { enabled: true, maxRetries: 3, baseBackoffMs: 50, backoffMultiplier: 2 },
        chaos: { isKilled: false, latencyJitterMs: 0, errorInjectionRate: 0, isPartitioned: false },
        circuitBreaker: { enabled: false, state: 'CLOSED', failureThreshold: 5, consecutiveFailures: 0, resetTimeoutMs: 5000, lastStateChange: Date.now(), probeRequestsAllowed: 3 },
        rateLimiter: { enabled: true, capacity: 5000, tokens: 4920, refillRatePerSec: 5000 },
        dockerImage: 'node:20-alpine',
      },
      {
        id: 'node-cdn',
        name: 'Cloudflare Edge CDN',
        type: 'cdn',
        category: 'network',
        region: 'us-east-1',
        x: 330,
        y: 280,
        width: 180,
        height: 105,
        status: 'healthy',
        techStack: ['Cloudflare Workers', 'Wasm', 'Anycast DNS'],
        ownerTeam: 'Edge Infra',
        tier: 'Tier 1 (Mission Critical)',
        description: 'Global edge network providing DDoS protection, WAF inspection, static asset delivery, and SSL termination.',
        runbook: '### Edge CDN Runbook\n- Check Cloudflare status dashboard.\n- If Origin is saturated, elevate Edge Cache TTL from 60s to 300s.\n- Enable Under-Attack mode in case of Layer 7 flood.',
        endpoints: [
          { id: 'ep-edge-1', method: 'GET', path: '/*', latencyMs: 8, statusCode: 200, description: 'Edge cached assets and proxy' }
        ],
        metrics: {
          currentRps: 2450,
          avgLatencyMs: 8,
          errorRate: 0.0005,
          cpuPercent: 22,
          memoryMb: 512,
          maxMemoryMb: 2048,
          activeConnections: 18400,
          queueDepth: 0,
          cacheHitRate: 0.84,
          currentReplicas: 4,
        },
        processing: {
          baseProcessingTimeMs: 6,
          concurrencyLimit: 8000,
          workerThreads: 16,
          cacheHitRate: 0.84,
        },
        autoscaling: { enabled: true, minReplicas: 4, maxReplicas: 16, cpuThresholdPercent: 75, scaleUpCooldownMs: 5000, lastScaleTime: 0 },
        connectionPool: { enabled: false, maxPoolSize: 200, activeConnections: 0, connectionTimeoutMs: 500 },
        retryPolicy: { enabled: true, maxRetries: 2, baseBackoffMs: 20, backoffMultiplier: 1.5 },
        chaos: { isKilled: false, latencyJitterMs: 0, errorInjectionRate: 0, isPartitioned: false },
        circuitBreaker: { enabled: false, state: 'CLOSED', failureThreshold: 10, consecutiveFailures: 0, resetTimeoutMs: 5000, lastStateChange: Date.now(), probeRequestsAllowed: 5 },
        rateLimiter: { enabled: true, capacity: 10000, tokens: 9500, refillRatePerSec: 10000 },
        dockerImage: 'cloudflare/cloudflared:latest',
      },
      {
        id: 'node-gateway',
        name: 'Kong API Gateway',
        type: 'gateway',
        category: 'network',
        region: 'us-east-1',
        x: 590,
        y: 280,
        width: 185,
        height: 105,
        status: 'healthy',
        techStack: ['Kong 3.4', 'OpenResty', 'Lua JIT'],
        ownerTeam: 'Platform Engineering',
        tier: 'Tier 1 (Mission Critical)',
        description: 'Central ingress routing, JWT token verification, dynamic rate limiting, and distributed tracing injection.',
        runbook: '### API Gateway Runbook\n- Verify upstream target health via `/status`.\n- If downstream latency spikes, check upstream connection pool limits.\n- In emergency, enable degraded mode serving cached catalog responses.',
        endpoints: [
          { id: 'ep-gw-1', method: 'POST', path: '/api/v1/auth/login', latencyMs: 25, statusCode: 200, description: 'Forward to Auth Service' },
          { id: 'ep-gw-2', method: 'GET', path: '/api/v1/orders', latencyMs: 45, statusCode: 200, description: 'Forward to Orders Service' },
          { id: 'ep-gw-3', method: 'POST', path: '/api/v1/checkout', latencyMs: 65, statusCode: 201, description: 'Forward to Payments Service' }
        ],
        metrics: {
          currentRps: 1890,
          avgLatencyMs: 16,
          errorRate: 0.002,
          cpuPercent: 35,
          memoryMb: 850,
          maxMemoryMb: 2048,
          activeConnections: 9200,
          queueDepth: 2,
          currentReplicas: 3,
        },
        processing: {
          baseProcessingTimeMs: 12,
          concurrencyLimit: 2500,
          workerThreads: 8,
        },
        autoscaling: { enabled: true, minReplicas: 3, maxReplicas: 8, cpuThresholdPercent: 70, scaleUpCooldownMs: 6000, lastScaleTime: 0 },
        connectionPool: { enabled: true, maxPoolSize: 100, activeConnections: 12, connectionTimeoutMs: 300 },
        retryPolicy: { enabled: true, maxRetries: 3, baseBackoffMs: 40, backoffMultiplier: 2 },
        chaos: { isKilled: false, latencyJitterMs: 0, errorInjectionRate: 0, isPartitioned: false },
        circuitBreaker: { enabled: true, state: 'CLOSED', failureThreshold: 5, consecutiveFailures: 0, resetTimeoutMs: 8000, lastStateChange: Date.now(), probeRequestsAllowed: 3 },
        rateLimiter: { enabled: true, capacity: 3000, tokens: 2800, refillRatePerSec: 3000 },
        dockerImage: 'kong:3.4-alpine',
      },
      {
        id: 'node-auth',
        name: 'Auth & Identity Service',
        type: 'service',
        category: 'compute',
        region: 'us-east-1',
        x: 860,
        y: 110,
        width: 195,
        height: 100,
        status: 'healthy',
        techStack: ['Go 1.22', 'JWT', 'gRPC', 'OIDC'],
        ownerTeam: 'Security & Auth',
        tier: 'Tier 1 (Mission Critical)',
        description: 'High-throughput OAuth2/OIDC token verification and user permission claim evaluation.',
        runbook: '### Auth Service Runbook\n- If Redis session store fails, fallback to stateless JWT RS256 signature verification.\n- Check asymmetric key rotation schedule.\n- Monitor failed login spikes for credential stuffing attacks.',
        endpoints: [
          { id: 'ep-auth-1', method: 'POST', path: '/auth/verify', latencyMs: 8, statusCode: 200, description: 'Token validation via gRPC' },
          { id: 'ep-auth-2', method: 'POST', path: '/auth/token', latencyMs: 32, statusCode: 200, description: 'Issue access & refresh tokens' }
        ],
        metrics: {
          currentRps: 780,
          avgLatencyMs: 14,
          errorRate: 0.001,
          cpuPercent: 24,
          memoryMb: 320,
          maxMemoryMb: 1024,
          activeConnections: 2400,
          queueDepth: 0,
          currentReplicas: 2,
        },
        processing: {
          baseProcessingTimeMs: 10,
          concurrencyLimit: 1200,
          workerThreads: 8,
        },
        autoscaling: { enabled: true, minReplicas: 2, maxReplicas: 6, cpuThresholdPercent: 65, scaleUpCooldownMs: 5000, lastScaleTime: 0 },
        connectionPool: { enabled: true, maxPoolSize: 40, activeConnections: 6, connectionTimeoutMs: 200 },
        retryPolicy: { enabled: true, maxRetries: 2, baseBackoffMs: 30, backoffMultiplier: 1.5 },
        chaos: { isKilled: false, latencyJitterMs: 0, errorInjectionRate: 0, isPartitioned: false },
        circuitBreaker: { enabled: true, state: 'CLOSED', failureThreshold: 6, consecutiveFailures: 0, resetTimeoutMs: 6000, lastStateChange: Date.now(), probeRequestsAllowed: 2 },
        rateLimiter: { enabled: true, capacity: 1500, tokens: 1400, refillRatePerSec: 1500 },
        dockerImage: 'golang:1.22-alpine',
      },
      {
        id: 'node-order',
        name: 'Order Orchestration',
        type: 'service',
        category: 'compute',
        region: 'us-east-1',
        x: 860,
        y: 280,
        width: 195,
        height: 100,
        status: 'healthy',
        techStack: ['Node.js 20', 'NestJS', 'TypeScript', 'Prisma'],
        ownerTeam: 'Checkout Team',
        tier: 'Tier 1 (Mission Critical)',
        description: 'Implements Saga pattern for distributed order state management, basket calculations, and inventory reservation.',
        runbook: '### Order Service Runbook\n- If Payment Service is degraded, buffer checkout transactions in Kafka Saga topic.\n- Never fail an order silently; ensure idempotency keys are stored in Redis.',
        endpoints: [
          { id: 'ep-ord-1', method: 'POST', path: '/orders', latencyMs: 62, statusCode: 201, description: 'Create and orchestrate order' },
          { id: 'ep-ord-2', method: 'GET', path: '/orders/:id', latencyMs: 18, statusCode: 200, description: 'Fetch order status' }
        ],
        metrics: {
          currentRps: 620,
          avgLatencyMs: 38,
          errorRate: 0.003,
          cpuPercent: 42,
          memoryMb: 680,
          maxMemoryMb: 2048,
          activeConnections: 3100,
          queueDepth: 4,
          currentReplicas: 3,
        },
        processing: {
          baseProcessingTimeMs: 35,
          concurrencyLimit: 800,
          workerThreads: 4,
        },
        autoscaling: { enabled: true, minReplicas: 2, maxReplicas: 8, cpuThresholdPercent: 70, scaleUpCooldownMs: 5000, lastScaleTime: 0 },
        connectionPool: { enabled: true, maxPoolSize: 50, activeConnections: 18, connectionTimeoutMs: 400 },
        retryPolicy: { enabled: true, maxRetries: 3, baseBackoffMs: 100, backoffMultiplier: 2 },
        chaos: { isKilled: false, latencyJitterMs: 0, errorInjectionRate: 0, isPartitioned: false },
        circuitBreaker: { enabled: true, state: 'CLOSED', failureThreshold: 5, consecutiveFailures: 0, resetTimeoutMs: 10000, lastStateChange: Date.now(), probeRequestsAllowed: 2 },
        rateLimiter: { enabled: true, capacity: 1200, tokens: 1100, refillRatePerSec: 1200 },
        dockerImage: 'node:20-alpine',
      },
      {
        id: 'node-payment',
        name: 'Payment Processing',
        type: 'service',
        category: 'compute',
        region: 'us-east-1',
        x: 860,
        y: 450,
        width: 195,
        height: 100,
        status: 'healthy',
        techStack: ['Rust 1.77', 'Axum', 'Tokio', 'OpenSSL'],
        ownerTeam: 'Fintech Core',
        tier: 'Tier 1 (Mission Critical)',
        description: 'PCI-DSS compliant payment processing engine, tokenized cards, and dynamic settlement orchestration.',
        runbook: '### Payment Processing Runbook\n- Circuit Breaker auto-activates if Stripe API error rate exceeds 8%.\n- Queue deferred transactions in Dead Letter Queue (DLQ).\n- Alert security officer on unexpected currency conversions.',
        endpoints: [
          { id: 'ep-pay-1', method: 'POST', path: '/payments/charge', latencyMs: 140, statusCode: 200, description: 'Execute payment transaction' },
          { id: 'ep-pay-2', method: 'POST', path: '/payments/webhook', latencyMs: 30, statusCode: 200, description: 'Handle gateway webhooks' }
        ],
        metrics: {
          currentRps: 490,
          avgLatencyMs: 85,
          errorRate: 0.002,
          cpuPercent: 28,
          memoryMb: 280,
          maxMemoryMb: 1024,
          activeConnections: 1800,
          queueDepth: 1,
          currentReplicas: 2,
        },
        processing: {
          baseProcessingTimeMs: 45,
          concurrencyLimit: 400,
          workerThreads: 8,
        },
        autoscaling: { enabled: true, minReplicas: 2, maxReplicas: 6, cpuThresholdPercent: 65, scaleUpCooldownMs: 5000, lastScaleTime: 0 },
        connectionPool: { enabled: true, maxPoolSize: 30, activeConnections: 8, connectionTimeoutMs: 300 },
        retryPolicy: { enabled: true, maxRetries: 2, baseBackoffMs: 150, backoffMultiplier: 2 },
        chaos: { isKilled: false, latencyJitterMs: 0, errorInjectionRate: 0, isPartitioned: false },
        circuitBreaker: { enabled: true, state: 'CLOSED', failureThreshold: 4, consecutiveFailures: 0, resetTimeoutMs: 12000, lastStateChange: Date.now(), probeRequestsAllowed: 2 },
        rateLimiter: { enabled: true, capacity: 800, tokens: 750, refillRatePerSec: 800 },
        dockerImage: 'rust:1.77-slim',
      },
      {
        id: 'node-redis',
        name: 'Redis Cluster (Cache)',
        type: 'cache',
        category: 'storage',
        region: 'us-east-1',
        x: 1160,
        y: 110,
        width: 185,
        height: 100,
        status: 'healthy',
        techStack: ['Redis 7.2', 'Cluster Mode', 'RDB/AOF'],
        ownerTeam: 'Data Infrastructure',
        tier: 'Tier 1 (Mission Critical)',
        description: 'In-memory multi-master cache for sessions, user authorization tokens, and product inventory counters.',
        runbook: '### Redis Cache Runbook\n- If memory reaches 85% of maxmemory, inspect eviction policy (`volatile-lru`).\n- In case of network partition, Sentinel will promote slave in < 3s.',
        endpoints: [],
        metrics: {
          currentRps: 1800,
          avgLatencyMs: 1.8,
          errorRate: 0.0001,
          cpuPercent: 32,
          memoryMb: 3840,
          maxMemoryMb: 8192,
          activeConnections: 4500,
          queueDepth: 0,
          cacheHitRate: 0.94,
          currentReplicas: 3,
        },
        processing: {
          baseProcessingTimeMs: 2,
          concurrencyLimit: 5000,
          workerThreads: 4,
          cacheHitRate: 0.94,
        },
        autoscaling: { enabled: false, minReplicas: 3, maxReplicas: 6, cpuThresholdPercent: 80, scaleUpCooldownMs: 10000, lastScaleTime: 0 },
        connectionPool: { enabled: false, maxPoolSize: 500, activeConnections: 0, connectionTimeoutMs: 100 },
        retryPolicy: { enabled: true, maxRetries: 2, baseBackoffMs: 10, backoffMultiplier: 1.5 },
        chaos: { isKilled: false, latencyJitterMs: 0, errorInjectionRate: 0, isPartitioned: false },
        circuitBreaker: { enabled: false, state: 'CLOSED', failureThreshold: 5, consecutiveFailures: 0, resetTimeoutMs: 5000, lastStateChange: Date.now(), probeRequestsAllowed: 3 },
        rateLimiter: { enabled: false, capacity: 10000, tokens: 10000, refillRatePerSec: 10000 },
        dockerImage: 'redis:7.2-alpine',
      },
      {
        id: 'node-kafka',
        name: 'Apache Kafka Event Bus',
        type: 'queue',
        category: 'queue',
        region: 'us-east-1',
        x: 1160,
        y: 280,
        width: 195,
        height: 100,
        status: 'healthy',
        techStack: ['Kafka 3.6', 'KRaft Mode', 'Schema Registry'],
        ownerTeam: 'Streaming Platform',
        tier: 'Tier 1 (Mission Critical)',
        description: 'High-throughput append-only distributed event stream. Topics: `orders.placed`, `payments.cleared`, `notifications.dispatch`.',
        runbook: '### Kafka Event Bus Runbook\n- Monitor consumer lag per partition with Burrow or Prometheus.\n- If lag > 10,000 msgs, auto-scale downstream consumer pods.',
        endpoints: [],
        metrics: {
          currentRps: 620,
          avgLatencyMs: 4.2,
          errorRate: 0.0002,
          cpuPercent: 38,
          memoryMb: 4200,
          maxMemoryMb: 8192,
          activeConnections: 3200,
          queueDepth: 12,
          currentReplicas: 3,
        },
        processing: {
          baseProcessingTimeMs: 4,
          concurrencyLimit: 4000,
          workerThreads: 8,
        },
        autoscaling: { enabled: true, minReplicas: 3, maxReplicas: 6, cpuThresholdPercent: 75, scaleUpCooldownMs: 8000, lastScaleTime: 0 },
        connectionPool: { enabled: false, maxPoolSize: 200, activeConnections: 0, connectionTimeoutMs: 200 },
        retryPolicy: { enabled: true, maxRetries: 4, baseBackoffMs: 50, backoffMultiplier: 2 },
        chaos: { isKilled: false, latencyJitterMs: 0, errorInjectionRate: 0, isPartitioned: false },
        circuitBreaker: { enabled: false, state: 'CLOSED', failureThreshold: 5, consecutiveFailures: 0, resetTimeoutMs: 5000, lastStateChange: Date.now(), probeRequestsAllowed: 3 },
        rateLimiter: { enabled: false, capacity: 5000, tokens: 5000, refillRatePerSec: 5000 },
        dockerImage: 'confluentinc/cp-kafka:7.5.0',
      },
      {
        id: 'node-postgres',
        name: 'PostgreSQL Primary Cluster',
        type: 'database',
        category: 'storage',
        region: 'us-east-1',
        x: 1160,
        y: 450,
        width: 195,
        height: 100,
        status: 'healthy',
        techStack: ['PostgreSQL 16', 'PgBouncer', 'Patroni HA'],
        ownerTeam: 'DBA & Core Data',
        tier: 'Tier 1 (Mission Critical)',
        description: 'Relational ACID store with multi-AZ synchronous replication, hot standby read replicas, and connection pooling.',
        runbook: '### Database Failover Runbook\n- If primary node heartbeat is lost for 10s, Patroni auto-promotes Read Replica 01 to Master.\n- PgBouncer reroutes pool connections seamlessly in < 1500ms.',
        endpoints: [],
        metrics: {
          currentRps: 580,
          avgLatencyMs: 14.5,
          errorRate: 0.001,
          cpuPercent: 54,
          memoryMb: 6100,
          maxMemoryMb: 12288,
          activeConnections: 380,
          queueDepth: 3,
          currentReplicas: 2,
        },
        processing: {
          baseProcessingTimeMs: 15,
          concurrencyLimit: 200,
          workerThreads: 4,
        },
        autoscaling: { enabled: false, minReplicas: 2, maxReplicas: 4, cpuThresholdPercent: 80, scaleUpCooldownMs: 15000, lastScaleTime: 0 },
        connectionPool: { enabled: true, maxPoolSize: 40, activeConnections: 22, connectionTimeoutMs: 250 },
        retryPolicy: { enabled: true, maxRetries: 3, baseBackoffMs: 80, backoffMultiplier: 2 },
        chaos: { isKilled: false, latencyJitterMs: 0, errorInjectionRate: 0, isPartitioned: false },
        circuitBreaker: { enabled: true, state: 'CLOSED', failureThreshold: 5, consecutiveFailures: 0, resetTimeoutMs: 8000, lastStateChange: Date.now(), probeRequestsAllowed: 2 },
        rateLimiter: { enabled: false, capacity: 2000, tokens: 2000, refillRatePerSec: 2000 },
        dockerImage: 'postgres:16-alpine',
      },
      {
        id: 'node-stripe',
        name: 'Stripe Payment Gateway',
        type: 'external',
        category: 'external',
        region: 'us-west-2',
        x: 1440,
        y: 450,
        width: 175,
        height: 100,
        status: 'healthy',
        techStack: ['Stripe API v2024', 'TLS 1.3', 'REST Webhooks'],
        ownerTeam: 'External Provider',
        tier: 'Tier 1 (Mission Critical)',
        description: 'External payment acquirer and fraud detection (Radar) API for global card authorization.',
        runbook: '### Stripe API External Outage Runbook\n- Check https://status.stripe.com\n- If 5xx response rate > 10%, fallback to secondary provider (Adyen).\n- Activate asynchronous delayed capture mode.',
        endpoints: [
          { id: 'ep-ext-1', method: 'POST', path: 'https://api.stripe.com/v1/charges', latencyMs: 240, statusCode: 200, description: 'Card authorization' }
        ],
        metrics: {
          currentRps: 240,
          avgLatencyMs: 195,
          errorRate: 0.004,
          cpuPercent: 12,
          memoryMb: 128,
          maxMemoryMb: 512,
          activeConnections: 450,
          queueDepth: 0,
          currentReplicas: 1,
        },
        processing: {
          baseProcessingTimeMs: 180,
          concurrencyLimit: 300,
          workerThreads: 4,
        },
        autoscaling: { enabled: false, minReplicas: 1, maxReplicas: 1, cpuThresholdPercent: 90, scaleUpCooldownMs: 10000, lastScaleTime: 0 },
        connectionPool: { enabled: false, maxPoolSize: 100, activeConnections: 0, connectionTimeoutMs: 500 },
        retryPolicy: { enabled: true, maxRetries: 2, baseBackoffMs: 200, backoffMultiplier: 2 },
        chaos: { isKilled: false, latencyJitterMs: 0, errorInjectionRate: 0, isPartitioned: false },
        circuitBreaker: { enabled: true, state: 'CLOSED', failureThreshold: 4, consecutiveFailures: 0, resetTimeoutMs: 15000, lastStateChange: Date.now(), probeRequestsAllowed: 2 },
        rateLimiter: { enabled: true, capacity: 600, tokens: 580, refillRatePerSec: 600 },
        dockerImage: 'external-api',
      }
    ],
    edges: [
      { id: 'edge-client-cdn', from: 'node-client', to: 'node-cdn', protocol: 'HTTP/2', baseLatencyMs: 14, bandwidthLimitRps: 5000, routingProbability: 1.0, status: 'active', label: 'HTTPS / TLS 1.3' },
      { id: 'edge-cdn-gw', from: 'node-cdn', to: 'node-gateway', protocol: 'HTTP/2', baseLatencyMs: 8, bandwidthLimitRps: 4000, routingProbability: 0.35, status: 'active', label: 'Origin Dynamic Pass' },
      { id: 'edge-gw-auth', from: 'node-gateway', to: 'node-auth', protocol: 'gRPC', baseLatencyMs: 6, bandwidthLimitRps: 2000, routingProbability: 0.45, status: 'active', label: 'Token Inspect (gRPC)' },
      { id: 'edge-gw-order', from: 'node-gateway', to: 'node-order', protocol: 'HTTP/2', baseLatencyMs: 12, bandwidthLimitRps: 1500, routingProbability: 0.35, status: 'active', label: 'REST Checkout' },
      { id: 'edge-gw-payment', from: 'node-gateway', to: 'node-payment', protocol: 'HTTP/2', baseLatencyMs: 15, bandwidthLimitRps: 1000, routingProbability: 0.2, status: 'active', label: 'Direct Charge' },
      { id: 'edge-auth-redis', from: 'node-auth', to: 'node-redis', protocol: 'Redis', baseLatencyMs: 2, bandwidthLimitRps: 5000, routingProbability: 0.9, status: 'active', label: 'Session Cache' },
      { id: 'edge-order-redis', from: 'node-order', to: 'node-redis', protocol: 'Redis', baseLatencyMs: 2, bandwidthLimitRps: 4000, routingProbability: 0.6, status: 'active', label: 'Inventory Cache' },
      { id: 'edge-order-kafka', from: 'node-order', to: 'node-kafka', protocol: 'Kafka', baseLatencyMs: 5, bandwidthLimitRps: 3000, routingProbability: 0.8, status: 'active', label: 'orders.created' },
      { id: 'edge-order-postgres', from: 'node-order', to: 'node-postgres', protocol: 'TCP/SQL', baseLatencyMs: 10, bandwidthLimitRps: 1500, routingProbability: 0.7, status: 'active', label: 'Order Entity Write' },
      { id: 'edge-kafka-payment', from: 'node-kafka', to: 'node-payment', protocol: 'Kafka', baseLatencyMs: 4, bandwidthLimitRps: 2000, routingProbability: 0.8, status: 'active', label: 'Order Stream Consumer' },
      { id: 'edge-payment-postgres', from: 'node-payment', to: 'node-postgres', protocol: 'TCP/SQL', baseLatencyMs: 11, bandwidthLimitRps: 1200, routingProbability: 0.5, status: 'active', label: 'Ledger Audit Write' },
      { id: 'edge-payment-stripe', from: 'node-payment', to: 'node-stripe', protocol: 'HTTP/2', baseLatencyMs: 45, bandwidthLimitRps: 600, routingProbability: 0.9, status: 'active', label: 'Cross-Region API' },
    ]
  },
  {
    id: 'resilient-mesh',
    name: 'Chaos & Autoscaling Lab',
    description: 'Demonstrating horizontal pod autoscaling under load spikes, cascading failure isolation, and circuit breakers.',
    badge: 'Autoscaling Lab',
    nodes: [
      {
        id: 'cm-client',
        name: 'Traffic Generator',
        type: 'client',
        category: 'client',
        region: 'us-east-1',
        x: 100,
        y: 260,
        width: 175,
        height: 105,
        status: 'healthy',
        techStack: ['k6 Engine', 'TypeScript'],
        ownerTeam: 'QA & Reliability',
        tier: 'Tier 3 (Standard)',
        description: 'Simulates heavy concurrent load with configurable burst spikes.',
        runbook: 'Inspect latency graphs during chaos drills.',
        endpoints: [],
        metrics: { currentRps: 3200, avgLatencyMs: 22, errorRate: 0.0, cpuPercent: 15, memoryMb: 180, maxMemoryMb: 1024, activeConnections: 12000, queueDepth: 0, currentReplicas: 2 },
        processing: { baseProcessingTimeMs: 2, concurrencyLimit: 5000, workerThreads: 8, clientGeneratedRps: 3200 },
        autoscaling: { enabled: true, minReplicas: 2, maxReplicas: 10, cpuThresholdPercent: 70, scaleUpCooldownMs: 5000, lastScaleTime: 0 },
        connectionPool: { enabled: false, maxPoolSize: 100, activeConnections: 0, connectionTimeoutMs: 500 },
        retryPolicy: { enabled: true, maxRetries: 3, baseBackoffMs: 50, backoffMultiplier: 2 },
        chaos: { isKilled: false, latencyJitterMs: 0, errorInjectionRate: 0, isPartitioned: false },
        circuitBreaker: { enabled: false, state: 'CLOSED', failureThreshold: 5, consecutiveFailures: 0, resetTimeoutMs: 5000, lastStateChange: Date.now(), probeRequestsAllowed: 3 },
        rateLimiter: { enabled: false, capacity: 5000, tokens: 5000, refillRatePerSec: 5000 },
        dockerImage: 'grafana/k6:latest',
      },
      {
        id: 'cm-gateway',
        name: 'Envoy Edge Proxy',
        type: 'gateway',
        category: 'network',
        region: 'us-east-1',
        x: 360,
        y: 260,
        width: 185,
        height: 105,
        status: 'healthy',
        techStack: ['Envoy Proxy', 'C++', 'gRPC-web'],
        ownerTeam: 'Platform Infra',
        tier: 'Tier 1 (Mission Critical)',
        description: 'Resilient edge ingress with outlier detection and active health checking.',
        runbook: 'Envoy drops unhealthy upstreams automatically after 3 consecutive 503s.',
        endpoints: [
          { id: 'ep-envoy-1', method: 'GET', path: '/v1/recommendations', latencyMs: 35, statusCode: 200, description: 'Aggregated recommendations' }
        ],
        metrics: { currentRps: 3200, avgLatencyMs: 24, errorRate: 0.001, cpuPercent: 28, memoryMb: 450, maxMemoryMb: 2048, activeConnections: 12000, queueDepth: 1, currentReplicas: 3 },
        processing: { baseProcessingTimeMs: 8, concurrencyLimit: 4000, workerThreads: 16 },
        autoscaling: { enabled: true, minReplicas: 3, maxReplicas: 8, cpuThresholdPercent: 70, scaleUpCooldownMs: 5000, lastScaleTime: 0 },
        connectionPool: { enabled: true, maxPoolSize: 100, activeConnections: 20, connectionTimeoutMs: 300 },
        retryPolicy: { enabled: true, maxRetries: 3, baseBackoffMs: 30, backoffMultiplier: 1.5 },
        chaos: { isKilled: false, latencyJitterMs: 0, errorInjectionRate: 0, isPartitioned: false },
        circuitBreaker: { enabled: true, state: 'CLOSED', failureThreshold: 5, consecutiveFailures: 0, resetTimeoutMs: 8000, lastStateChange: Date.now(), probeRequestsAllowed: 2 },
        rateLimiter: { enabled: true, capacity: 4000, tokens: 3800, refillRatePerSec: 4000 },
        dockerImage: 'envoyproxy/envoy:v1.28-latest',
      },
      {
        id: 'cm-service-a',
        name: 'Recommendation Service',
        type: 'service',
        category: 'compute',
        region: 'us-east-1',
        x: 640,
        y: 180,
        width: 200,
        height: 105,
        status: 'healthy',
        techStack: ['Python 3.12', 'FastAPI', 'PyTorch'],
        ownerTeam: 'Data Science & Recs',
        tier: 'Tier 2 (High Priority)',
        description: 'ML model service predicting user preferences with real-time vector embeddings.',
        runbook: 'If legacy model downstream fails, return static curated fallback list in < 15ms.',
        endpoints: [
          { id: 'ep-rec-1', method: 'POST', path: '/predict', latencyMs: 48, statusCode: 200, description: 'Personalized recommendations' }
        ],
        metrics: { currentRps: 1600, avgLatencyMs: 45, errorRate: 0.002, cpuPercent: 44, memoryMb: 1200, maxMemoryMb: 4096, activeConnections: 2200, queueDepth: 5, currentReplicas: 2 },
        processing: { baseProcessingTimeMs: 40, concurrencyLimit: 1200, workerThreads: 8 },
        autoscaling: { enabled: true, minReplicas: 2, maxReplicas: 8, cpuThresholdPercent: 65, scaleUpCooldownMs: 4000, lastScaleTime: 0 },
        connectionPool: { enabled: true, maxPoolSize: 40, activeConnections: 15, connectionTimeoutMs: 300 },
        retryPolicy: { enabled: true, maxRetries: 2, baseBackoffMs: 80, backoffMultiplier: 2 },
        chaos: { isKilled: false, latencyJitterMs: 0, errorInjectionRate: 0, isPartitioned: false },
        circuitBreaker: { enabled: true, state: 'CLOSED', failureThreshold: 4, consecutiveFailures: 0, resetTimeoutMs: 7000, lastStateChange: Date.now(), probeRequestsAllowed: 2 },
        rateLimiter: { enabled: true, capacity: 2000, tokens: 1900, refillRatePerSec: 2000 },
        dockerImage: 'python:3.12-slim',
      },
      {
        id: 'cm-service-b',
        name: 'Legacy Pricing Engine',
        type: 'service',
        category: 'compute',
        region: 'eu-central-1',
        x: 940,
        y: 180,
        width: 195,
        height: 105,
        status: 'healthy',
        techStack: ['Java 21', 'Spring Boot 3', 'Hibernate'],
        ownerTeam: 'Legacy Core',
        tier: 'Tier 2 (High Priority)',
        description: 'Complex enterprise pricing and tax calculation logic with fragile legacy dependencies.',
        runbook: 'Subject to CPU exhaustion under high concurrency. Circuit breaker prevents it from crashing entire app.',
        endpoints: [
          { id: 'ep-price-1', method: 'GET', path: '/pricing/quote', latencyMs: 120, statusCode: 200, description: 'Dynamic price evaluation' }
        ],
        metrics: { currentRps: 820, avgLatencyMs: 95, errorRate: 0.015, cpuPercent: 68, memoryMb: 2400, maxMemoryMb: 4096, activeConnections: 1400, queueDepth: 14, currentReplicas: 1 },
        processing: { baseProcessingTimeMs: 85, concurrencyLimit: 400, workerThreads: 4 },
        autoscaling: { enabled: true, minReplicas: 1, maxReplicas: 4, cpuThresholdPercent: 75, scaleUpCooldownMs: 8000, lastScaleTime: 0 },
        connectionPool: { enabled: true, maxPoolSize: 20, activeConnections: 18, connectionTimeoutMs: 500 },
        retryPolicy: { enabled: true, maxRetries: 1, baseBackoffMs: 200, backoffMultiplier: 2 },
        chaos: { isKilled: false, latencyJitterMs: 0, errorInjectionRate: 0, isPartitioned: false },
        circuitBreaker: { enabled: true, state: 'CLOSED', failureThreshold: 3, consecutiveFailures: 0, resetTimeoutMs: 10000, lastStateChange: Date.now(), probeRequestsAllowed: 1 },
        rateLimiter: { enabled: true, capacity: 1000, tokens: 900, refillRatePerSec: 1000 },
        dockerImage: 'eclipse-temurin:21-jre-alpine',
      },
      {
        id: 'cm-service-c',
        name: 'User Profile Store',
        type: 'database',
        category: 'storage',
        region: 'us-east-1',
        x: 640,
        y: 370,
        width: 195,
        height: 100,
        status: 'healthy',
        techStack: ['MongoDB 7.0', 'WiredTiger', 'ReplicaSet'],
        ownerTeam: 'User Platform',
        tier: 'Tier 1 (Mission Critical)',
        description: 'Document store storing user behavioral vectors and telemetry history.',
        runbook: 'Secondary read preference enabled for non-critical query load.',
        endpoints: [],
        metrics: { currentRps: 1580, avgLatencyMs: 8.5, errorRate: 0.0005, cpuPercent: 30, memoryMb: 3100, maxMemoryMb: 8192, activeConnections: 640, queueDepth: 1, currentReplicas: 2 },
        processing: { baseProcessingTimeMs: 6, concurrencyLimit: 1500, workerThreads: 4 },
        autoscaling: { enabled: false, minReplicas: 2, maxReplicas: 4, cpuThresholdPercent: 80, scaleUpCooldownMs: 10000, lastScaleTime: 0 },
        connectionPool: { enabled: true, maxPoolSize: 60, activeConnections: 24, connectionTimeoutMs: 200 },
        retryPolicy: { enabled: true, maxRetries: 3, baseBackoffMs: 50, backoffMultiplier: 1.5 },
        chaos: { isKilled: false, latencyJitterMs: 0, errorInjectionRate: 0, isPartitioned: false },
        circuitBreaker: { enabled: false, state: 'CLOSED', failureThreshold: 5, consecutiveFailures: 0, resetTimeoutMs: 5000, lastStateChange: Date.now(), probeRequestsAllowed: 3 },
        rateLimiter: { enabled: false, capacity: 3000, tokens: 3000, refillRatePerSec: 3000 },
        dockerImage: 'mongo:7.0',
      },
      {
        id: 'cm-dlq',
        name: 'Dead Letter Queue (DLQ)',
        type: 'queue',
        category: 'queue',
        region: 'us-east-1',
        x: 940,
        y: 370,
        width: 195,
        height: 100,
        status: 'healthy',
        techStack: ['RabbitMQ 3.13', 'Erlang VM', 'Quorum Queues'],
        ownerTeam: 'Platform Infra',
        tier: 'Tier 1 (Mission Critical)',
        description: 'Absorbs rejected and timed-out requests when downstream services or circuit breakers are open.',
        runbook: 'Inspect queue depth. Run DLQ replay worker once legacy pricing engine recovers.',
        endpoints: [],
        metrics: { currentRps: 25, avgLatencyMs: 2.1, errorRate: 0.0, cpuPercent: 12, memoryMb: 480, maxMemoryMb: 2048, activeConnections: 120, queueDepth: 8, currentReplicas: 1 },
        processing: { baseProcessingTimeMs: 2, concurrencyLimit: 5000, workerThreads: 4 },
        autoscaling: { enabled: false, minReplicas: 1, maxReplicas: 2, cpuThresholdPercent: 80, scaleUpCooldownMs: 8000, lastScaleTime: 0 },
        connectionPool: { enabled: false, maxPoolSize: 100, activeConnections: 0, connectionTimeoutMs: 500 },
        retryPolicy: { enabled: false, maxRetries: 0, baseBackoffMs: 0, backoffMultiplier: 1 },
        chaos: { isKilled: false, latencyJitterMs: 0, errorInjectionRate: 0, isPartitioned: false },
        circuitBreaker: { enabled: false, state: 'CLOSED', failureThreshold: 5, consecutiveFailures: 0, resetTimeoutMs: 5000, lastStateChange: Date.now(), probeRequestsAllowed: 3 },
        rateLimiter: { enabled: false, capacity: 5000, tokens: 5000, refillRatePerSec: 5000 },
        dockerImage: 'rabbitmq:3.13-management-alpine',
      }
    ],
    edges: [
      { id: 'cm-edge-1', from: 'cm-client', to: 'cm-gateway', protocol: 'HTTP/2', baseLatencyMs: 18, bandwidthLimitRps: 4000, routingProbability: 1.0, status: 'active', label: 'Inbound Requests' },
      { id: 'cm-edge-2', from: 'cm-gateway', to: 'cm-service-a', protocol: 'gRPC', baseLatencyMs: 6, bandwidthLimitRps: 2000, routingProbability: 0.8, status: 'active', label: 'gRPC Predict' },
      { id: 'cm-edge-3', from: 'cm-service-a', to: 'cm-service-b', protocol: 'HTTP/2', baseLatencyMs: 55, bandwidthLimitRps: 1000, routingProbability: 0.6, status: 'active', label: 'Cross-Region (EU)' },
      { id: 'cm-edge-4', from: 'cm-service-a', to: 'cm-service-c', protocol: 'TCP/SQL', baseLatencyMs: 4, bandwidthLimitRps: 2000, routingProbability: 0.9, status: 'active', label: 'Fetch User Features' },
      { id: 'cm-edge-5', from: 'cm-service-b', to: 'cm-dlq', protocol: 'AMQP', baseLatencyMs: 3, bandwidthLimitRps: 1500, routingProbability: 0.3, status: 'active', label: 'Failover Spillover' },
    ]
  },
  {
    id: 'blank-canvas',
    name: 'Blank Canvas (Custom Architecture)',
    description: 'Start from scratch! Add custom microservices, databases, gateways, and draw custom interconnects.',
    badge: 'Custom Project',
    nodes: [],
    edges: []
  }
];
